name: Deploy Documentation
on: [push]

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Trigger workflow dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          repository: LunarClient/lunarclient.dev-Build
          inputs: '{"github": ${{ toJson(github) }}}'
          token: ${{ secrets.DISPATCH_TOKEN }}
