name: Deploy Documentation
on: [push]

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Trigger Documentation Deploy
        uses: moonsworth/actions/deploy-lc-docs@master
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
